// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPNt2nvH-qNQPHBjZEsfrzO8bYJt805JI',
    appId: '1:361108049818:web:d72e73797f24ab1584f423',
    messagingSenderId: '361108049818',
    projectId: 'ikarus-milyem-672ff',
    authDomain: 'ikarus-milyem-672ff.firebaseapp.com',
    storageBucket: 'ikarus-milyem-672ff.firebasestorage.app',
    measurementId: 'G-S0WP821W8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr-ZiVJHuX5h7iwARy5yvuBTyT4aOGPCk',
    appId: '1:361108049818:android:1d92db96d33b70c984f423',
    messagingSenderId: '361108049818',
    projectId: 'ikarus-milyem-672ff',
    storageBucket: 'ikarus-milyem-672ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAzeEkcCT5oAHZ6XApwIsE2MGpbOBXWlc',
    appId: '1:361108049818:ios:f7949d8095ecb98584f423',
    messagingSenderId: '361108049818',
    projectId: 'ikarus-milyem-672ff',
    storageBucket: 'ikarus-milyem-672ff.firebasestorage.app',
    iosBundleId: 'ikarus.ikarusMilyem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAzeEkcCT5oAHZ6XApwIsE2MGpbOBXWlc',
    appId: '1:361108049818:ios:f7949d8095ecb98584f423',
    messagingSenderId: '361108049818',
    projectId: 'ikarus-milyem-672ff',
    storageBucket: 'ikarus-milyem-672ff.firebasestorage.app',
    iosBundleId: 'ikarus.ikarusMilyem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPNt2nvH-qNQPHBjZEsfrzO8bYJt805JI',
    appId: '1:361108049818:web:8fbfdf6a8e14335084f423',
    messagingSenderId: '361108049818',
    projectId: 'ikarus-milyem-672ff',
    authDomain: 'ikarus-milyem-672ff.firebaseapp.com',
    storageBucket: 'ikarus-milyem-672ff.firebasestorage.app',
    measurementId: 'G-162ZNSW77E',
  );
}
